language: c
os: linux
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
# Blacklist
branches:
  except:
    - gh-pages
git:
  depth: false
  quiet: true
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - python3-pip
      - python3-wheel
      - clang-format-5.0
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.15"
     - PRETTYNAME="Arduino TR-064 Library"
     - SECRET_WIFI_SSID="WLANSID"
     - SECRET_WIFI_PASSWORD="XXXXXXXXXXXXXXXXXXXXX"
     - SECRET_FUSER="homechecker"
     - SECRET_FPASS="this_shouldBEaDecentPassword!"
     - SECRET_IP="192.168.178.1"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
 
before_install:
   #- chmod +x makesecret.sh
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   
install:
   - arduino --install-library "ConfigManager"
 
script:
   - make 
   - build_platform esp8266
   - build_platform esp32
 
# Generate and deploy documentation
after_success:
  # Currently not doing anything
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  # Now create doxy documentation
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
